### ISSUE TITLE
Possible multiple enumeration

### ISSUE THREAD

**Issue by dmitry-bym** [ardalis/GuardClauses#126]
- .NET SDK Version: net5

Steps to Reproduce
![Screenshot_157](https://user-images.githubusercontent.com/43404211/135037166-62a18d7d-f088-4341-8b42-daea7a192818.png)

it will show possible multiple enumeration. I see that you use JBanotations let's add NoEnumeration attribute for methods

**Comment by ardalis** [comment]
If it's just doing a null check it shouldn't enumerate so it shouldn't be a problem in the code you posted. I'm not familiar with the attribute you're suggesting but if it solves a real issue I'm happy to add it.

**Comment by dmitry-bym** [comment]
Yes, i mean actually there is no enumeration. But analizer says that it may be. i mean it cant look deep into the method. When we add the attribute we will say to analizer that there is no enumeration inside our method. So the reason is when i do some check I do not want to see a warning about possible multiple enumeration. it will show this even here:
![Screenshot_158](https://user-images.githubusercontent.com/43404211/135316185-b11bdebc-dffc-4288-a77d-2ef0422b1a15.png)
After
![Screenshot_159](https://user-images.githubusercontent.com/43404211/135316160-435d010b-86f0-41d0-bec5-f2a6c51377ae.png)
I can create pr and do that. Wanted to discuss it first

**Comment by ardalis** [comment]
A PR would be perfect, thanks!

**Comment by dmitry-bym** [comment]
@ardalis did it
