### ISSUE TITLE
Confusing NullOrWhiteSpace

### ISSUE THREAD

**Issue by jsystem** [ardalis/GuardClauses#14]
I ended up changing my code many places due to the confusion made by NullOrWhiteSpace clause since my expectation had been this behaves like **string.IsNullOrWhiteSpace** but acutally it checks whitespaces _anywhere_ inside the string. Makes no sense to me anyways. 

so this yields exception unexpectedely:
Guard.Against.NullOrWhiteSpace("some white spaces but not empty", "foo");

I'd suggest you to change implementation to this:
public static void NullOrWhiteSpace(this IGuardClause guardClause, string input, string parameterName)
		{
			if (string.IsNullOrWhiteSpace(input))
			{
				throw new ArgumentException($"Required input {parameterName} was null, empty, or consists only of white-spacecharacters.", parameterName);
			}
		}

thanks,
Kornel

**Comment by ardalis** [comment]
Thanks, this appears to be a bug. I'll try and get it fixed this week unless you wanted to submit a PR with your proposed fix (and perhaps a unit test).

**Comment by ardalis** [comment]
Published package version 1.2.3. Thanks!
