### ISSUE TITLE
Employ `[CallerArgumentExpression]` attributes on `parameterName` parameters

### ISSUE THREAD

**Issue by tormodfj** [ardalis/GuardClauses#153]
The C# 10 compiler recognizes the [`CallerArgumentExpressionAttribute`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.callerargumentexpressionattribute). This can be used to render the `parameterName` parameters superfluous.

Without the attribute:
```csharp
_name = Guard.Against.NullOrWhiteSpace(name, nameof(name));
```

With the attribute:
```csharp
_name = Guard.Against.NullOrWhiteSpace(name);
```

If this attribute could be employed without breaking backwards compatibility, it would be a welcome addition to the library.

**Comment by tormodfj** [comment]
This article in CODE Magazine has a section explaining the use of `[CallerArgumentExpression]`:
[Essential C# 10.0: Making it Simpler](https://www.codemag.com/Article/2111052/Essential-C#-10.0-Making-it-Simpler)

**Comment by ardalis** [comment]
Yeah, here's another one.
https://weblogs.asp.net/dixin/csharp-10-new-feature-callerargumentexpression-argument-check-and-more

I think it will make a good alternate syntax, but I want to keep the previous syntax as well for at least one version so it doesn't break the world.

**Comment by pmcilreavy** [comment]
It's definitely useful, but it's not the same thing. It's the expression that was passed, not the name of the parameter.

**Comment by rafaelsc** [comment]
The biggest issue of implementation of this feature in GuardClauses is that can cause confusion with the `message` and `parameterName`. When omitting the parameterName in the attribute list.

```csharp
_name = Guard.Against.NullOrWhiteSpace(name, nameof(name), "Name is Invalid!");
````
```csharp
_name = Guard.Against.NullOrWhiteSpace(name, "Name is Invalid!"); 
// BUG - This will set the parameterName to "Name is Invalid!", not the error message.
```
```csharp
_name = Guard.Against.NullOrWhiteSpace(name, message: "Name is Invalid!""); // OK
```

**Comment by ardalis** [comment]
Is that improved if we use an extension?

```
_name = name.NotNullOrWhiteSpace("Name can't be empty");

// extension idea - not tested just writing in browser...
public static T NotNullOrWhiteSpace(this T input, string message, [CallerArgumentExpression] parameterName);
```

**Comment by tormodfj** [comment]
> Is that improved if we use an extension?
> 
> ```
> _name = name.NotNullOrWhiteSpace("Name can't be empty");
> 
> // extension idea - not tested just writing in browser...
> public static T NotNullOrWhiteSpace(this T input, string message, [CallerArgumentExpression] parameterName);
> ```

To further prevent any overload resolution issues, one could place such extension methods in a separate namespace, making the experience opt-in from a developer's point of view.

**Comment by DickBaker** [comment]
afaik that extension idea syntax should be [added =null!]
public static T NotNullOrWhiteSpace(this T input, string message, [CallerArgumentExpression] parameterName = null!);

**Comment by stap123** [comment]
related to #149

**Comment by ardalis** [comment]
The latest v4 version includes this code:

```csharp
#if NETSTANDARD || NETFRAMEWORK
        public static T Null<T>([JetBrainsNotNull] this IGuardClause guardClause,
            [NotNull, JetBrainsNotNull][ValidatedNotNull][JetBrainsNoEnumeration] T input,
            [JetBrainsNotNull][JetBrainsInvokerParameterName] string parameterName,
            string? message = null)
#else
        public static T Null<T>([JetBrainsNotNull] this IGuardClause guardClause,
            [NotNull, JetBrainsNotNull][ValidatedNotNull][JetBrainsNoEnumeration] T input,
            [JetBrainsNotNull][CallerArgumentExpression("input")] string? parameterName = null,
            string? message = null)
#endif
        {
            if (input is null)
            {
                if (string.IsNullOrEmpty(message))
                {
                    throw new ArgumentNullException(parameterName);
                }
                throw new ArgumentNullException(parameterName, message);
            }

            return input;
        }
```

Anyone running into issues with method resolution using this? All unit tests seem to work fine.

**Comment by djeikyb** [comment]
Not for null, but I'm missing the `[CallerArgumentExpression]` for the rest of the extension methods, like `NullOrEmpty` and `Negative`. I see them on main; looking forward to their release!

**Comment by danielmackay** [comment]
@djeikyb same here.  I've just updated to V4 and thought this would have been added throughout.  Would be a very nice addition to get this functionality across the board.

**Comment by ardalis** [comment]
I agree it should be added throughout. Open to PRs, or I'll get to it at some point.

**Comment by danielmackay** [comment]
@ardalis Any guidance on contributing via PR?  Feature branch on this repo?  Or PR from a branch on a forked repo?

**Comment by stap123** [comment]
@ardalis It's already been merged, we did the PR a while ago just wasn't released 🥲 It's sat in master waiting for a release 😄

**Comment by ardalis** [comment]
Hmm, I just did a release < 3 weeks ago. Wonder how that got missed / came in after. I'll try and push out a point release this week then, I guess.

**Comment by stap123** [comment]
ping @ardalis any chance of pushing that release soon? Sorry to nag 😕 thanks for all the work 😃

**Comment by ardalis** [comment]
Trying to deploy 4.0.1 now.

**Comment by ardalis** [comment]
GitHub action failed but the publish worked - 4.0.1 should be available momentarily!

https://github.com/ardalis/GuardClauses/runs/5723074640?check_suite_focus=true
