### ISSUE TITLE
A `NullOrInvalidValue` method

### ISSUE THREAD

**Issue by C0DK** [ardalis/GuardClauses#173]
I'd love to be able to get an ArgumentNullException when the value is null and a plain ArgumentException when it simply has some invalid form. My current best practice for this is:

```c#
Actions = Guard.Against.InvalidInput(
     Guard.Against.Null(actions, nameof(actions)),
     nameof(actions), HasNoDuplicates).ToList();
```

However, it is a bit cumbersome. It'd be nice to have a method that would make it possible to do:

```c#
Actions = Guard.Against.NullOrInvalidInput(actions, nameof(actions), HasNoDuplicates).ToList();
```

**Comment by sasagh** [comment]
Can I start working on this?

**Comment by ardalis** [comment]
In your example @C0DK what type is `HasNoDuplicates` ?

**Comment by C0DK** [comment]
`actions` is an `IEnumerable<T>`, where `T` was some custom class as far as I remember - `HasNoDuplicates` is a `Predicate<IEnumerable<T>>`

**Comment by victormarante** [comment]
@ardalis @C0DK Could we close this issue? PR #178 has been merged (has it been deployed?)

**Comment by C0DK** [comment]
Yes. Looks good.
