### ISSUE TITLE
NuGet package out of date?

### ISSUE THREAD

**Issue by scottkuhl** [ardalis/GuardClauses#20]
This method does not appear to be in the NuGet package:

public static void NullOrEmpty<T>(this IGuardClause guardClause, IEnumerable<T> input, string parameterName)

Is the NuGet package up to date?

**Comment by ardalis** [comment]
It's a few commits behind. I'll get a new version out this week, perhaps today. Thanks.

**Comment by ardalis** [comment]
Published - available shortly. 
![image](https://user-images.githubusercontent.com/782127/51612704-f9e40c80-1eef-11e9-93fb-dec95c602caa.png)

**Comment by terryjbutler** [comment]
Great work! Thank you!

**Comment by scottkuhl** [comment]
Awesome!  Nice turn around time.
