### ISSUE TITLE
Guard.Against.EnumOutOfRange()

### ISSUE THREAD

**Issue by ardalis** [ardalis/GuardClauses#25]
Ensure that an enum is in the range of the defined enum type.

See: https://stackoverflow.com/questions/2674730/is-there-a-way-to-check-if-int-is-legal-enum-in-c

**Comment by DavidColemanUK** [comment]
I fancied having a pop at this for my first github/OS contribution. 
Working on it now.

**Comment by ardalis** [comment]
Done now - thanks @DavidColemanUK
