### ISSUE TITLE
New and Better Logo

### ISSUE THREAD

**Issue by ardalis** [ardalis/GuardClauses#26]
The current logo appearing in nuget.org demonstrates my own design skills:

![image](https://user-images.githubusercontent.com/782127/51841542-e9aba300-22dc-11e9-9737-cc3dc3227ec3.png)

Since the project has been relatively successful and now has well over 50k downloads, a better logo is probably warranted. If someone would like to contribute one I'd appreciate it greatly. Just submit a PR with the logo assets in a subfolder and reference this issue. If there are several we'll try and pick the best of them. Thanks!

**Comment by mirzazulfan** [comment]
Hi @ardalis , I've designed a logo for your project, what do you think? if you need anything change please let me know.
![gc](https://user-images.githubusercontent.com/36124339/52034038-b9246d00-2559-11e9-9de9-f1b79004600c.png)

**Comment by ardalis** [comment]
Awesome, thanks! I'm not sure I love the color combo (I'm more partial to blues personally) but the graphic looks great. I'd love to get not just this image but also the source files and separate PNGs I can use for favicon and square icons like nuget.org displays. If that's cool you can submit everything in a PR and just put the files in a root `media` folder.

**Comment by mirzazulfan** [comment]
Thanks for your response @ardalis , I'll send all variation files and create a PR. As soon as possible. :+1: 
![logo](https://user-images.githubusercontent.com/36124339/52102738-ba66a000-2614-11e9-8880-6c42d928291f.png)

**Comment by ardalis** [comment]
I accepted #28, thanks! I think I'd prefer the bottom right orange/grey version if you don't mind. Can you do another quick PR with that scheme when you have a chance?
![image](https://user-images.githubusercontent.com/782127/52178047-6b954380-2797-11e9-9e9a-14066eead462.png)

**Comment by mirzazulfan** [comment]
Sure @ardalis .. i'll add it tomorrow.

**Comment by ardalis** [comment]
All set, thanks! Will be live on nuget.org after next deployment.
