### ISSUE TITLE
Make T nullable

### ISSUE THREAD

**Issue by ardalis** [ardalis/GuardClauses#260]
See: https://github.com/ardalis/GuardClauses/discussions/258#discussioncomment-5065114

Make `T` be `T?` so that nullable works properly in C# 9 and later.

**Comment by kawazoe** [comment]
Should probably be done for NotFound as well.

**Comment by ardalis** [comment]
Fixed by https://github.com/ardalis/GuardClauses/commit/3f44649ed522eed74a1d81ba81dd9a7a532ba013
