### ISSUE TITLE
Assign pull-requests: write permission to build action

### ISSUE THREAD

**Issue by amal-stack** [ardalis/GuardClauses#263]
For GitHub actions to comment on a PR, the `pull-requests: write` permission is required. See: [this discussion].(https://github.com/orgs/community/discussions/26644)
The lack of this permission is causing the `Resource not available by integration` error for the build action.
This permission can be added to *build.yml* as:
```
 permissions:
      pull-requests: write
``` 
I have tried this on my fork and the build passes and adds the comment successfully: https://github.com/amal-stack/GuardClauses/pull/2.

Also, see: [Assigning Permissions to Jobs](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs).

**Comment by ardalis** [comment]
Added to my build script, thanks! Need to test it out.

**Comment by amal-stack** [comment]
This is apparently due to a policy change by GitHub. See https://github.com/marocchino/sticky-pull-request-comment/issues/227.

**Comment by sadukie** [comment]
@ardalis It looks like I somehow added this back in March. It looks to be working, according to this PR: #283 

Looking at [past actions](https://github.com/ardalis/GuardClauses/actions?query=event%3Aworkflow_run)
- The ".NET Core" pipeline has more triggers than just a PR. Where it gets triggered in a non-PR trigger, the [comment to PR workflow is skipped](https://github.com/sadukie/GuardClauses/actions/runs/5718122286).
- The action will fail if it is triggered on its own. It relies on some steps in the ".NET Core" pipeline.

I think this issue can be closed.

**Comment by sadukie** [comment]
Added in this PR: #265
