### ISSUE TITLE
Support .NET 6, .NET 7 AND .NET 8?

### ISSUE THREAD

**Issue by bgoodearl** [ardalis/GuardClauses#319]
Rather than building for .NET 7 instead of .NET 6, how about supporting .NET 6, .NET 7 AND .NET 8 since all are currently supported frameworks?

I did a local build with both .NET 6 and .NET 8 and all of the unit tests pass.

**Comment by heischo** [comment]
See the csproj file:
`<TargetFrameworks>net8.0;netstandard2.1;netstandard2.0</TargetFrameworks>`
No problem with any version .NET 5+, because of netstandard2.1.

**Comment by ardalis** [comment]
Agreed this should work with any .NET version going back quite far at this point, since we support netstandard 2.0/2.1.
