### ISSUE TITLE
Setup CI/CD with Azure Pipelines

### ISSUE THREAD

**Issue by kasunkv** [ardalis/GuardClauses#32]
Hi @ardalis,
I read your post about [NuGet Publication Checklist](https://ardalis.com/nuget-publication-checklist?utm_campaign=meetedgar&utm_medium=social&utm_source=meetedgar.com) and thought we can set this up using Azure Pipelines. I see that you already have CI configured with Azure Pipelines. I was wondering if I can help out with setting up a release pipeline for it so you don't have to do it manually. 

Let me know if I am Ok to move ahead with it :)

**Comment by ardalis** [comment]
That would be awesome, thanks. I assume that's mainly just an update to the azure-pipelines.yml file?

Questions I have on this:

- How do I trigger a build? I'm assuming merging into a particular branch or creating a tagged release are my options. If the former, I would probably want to change the repo's defaults so that regular work occurred in a `dev` branch and releases were done by merging into `master` probably with a tagged branch number. Does that work? Better ideas? Is it possible for the tagged release bit to happen automatically as part of the process (with the tag matching the new package version number)?

- I assume I'd need to store a `nuget.org` key in Azure. How/where do I do that?

**Comment by kasunkv** [comment]
Yes it would update the existing azure-pipelines.yml file. We would do few changes to how the NuGet package is released. Here is what i am thinking at the moment.

* We need to separate the build and the release of the NuGet package. This way we can control the release of the package.
* We can keep the current branching strategy if you want, and merge PRs in to master
* The azure-pipelines.yml file will contain some tasks with conditions to only execute when not triggered from a PR build
* We can setup a release definition that is triggered only when a tag is pushed to the master branch that matches certain pattern. In this case your version number.
* But the Azure Pipelines Releases does not support YAML releases at the moment, but it will be coming in 2019. So we will have to create the release pipeline manually.
* The API key needed for pushing the NuGet package to public NuGet registry can be stored with in Azure DevOps. We can create a Service Connection for the this and use the Service Connection to push the NuGet package in to NuGet.org

I've forked this repository to my GitHub account, I'll create the CI and CD pipelines and give you a run down on how we would release and any issues if they present themselves. Please let me know what you think.

**Comment by ardalis** [comment]
Sounds good - looking forward to seeing it. Thanks!

**Comment by kasunkv** [comment]
Hi @ardalis, 

I think i am done.. :) Created the PR with the new CI pipeline. We need to create the release pipeline next. How should i proceed? Will i able to get provisional access to the https://dev.azure.com/ardalis to create the pipeline? Please have a look at the new pipeline and the build.

**Comment by ardalis** [comment]
I can probably get you access to my pipeline. Or you can just outline the steps I need to take here or in a new issue. To add you I probably need your email address.

**Comment by kasunkv** [comment]
My email address is kvkrusl[at]gmail.com I'm good with both Steve, what is your preference? Outlining the steps or me creating the release pipeline? :)

**Comment by ardalis** [comment]
Invite sent. :)

**Comment by kasunkv** [comment]
Confirmed to have access :) Thanks. Can you email me the API key for NuGet to create the service connection?
