### ISSUE TITLE
FluentValidation

### ISSUE THREAD

**Issue by ardalis** [ardalis/GuardClauses#324]
Add a Guard.Against.Invalid() that takes in a fluent validator type and performs something like:

```csharp
    validator!.ValidateAndThrow(input);
```

This would need to go into a new package, Ardalis.GuardClauses.FluentValidation

**Comment by AkhmedovEhson** [comment]
You mean, using FluentValidation package within Guard ?

**Comment by AkhmedovEhson** [comment]
> @ardalis You mean using 📦 `FluentValidation` package within Guard ? #334

**Comment by ardalis** [comment]
Note sure this is something worth doing especially since it blurs the lines between validation and guard clauses. See 

https://www.youtube.com/watch?v=dpPcnAT7n7M&ab_channel=Ardalis
