### ISSUE TITLE
MaxLengthExceeded / TooLong

### ISSUE THREAD

**Issue by ardalis** [ardalis/GuardClauses#325]
Add a Guard for strings that exceed a specified maximum length.

**Comment by Maarkis** [comment]
Hi @ardalis!
I added contribution #331, but I noticed that it has already been implemented by you... Feel free to close the request, if you want. 😃

**Comment by ardalis** [comment]
Yeah didn't see yours until after I did mine, sorry. Thanks for the contribution though!
