### ISSUE TITLE
LengthOutOfRange

### ISSUE THREAD

**Issue by ardalis** [ardalis/GuardClauses#327]
Add a string guard that supports both a min and max length of the string.

```csharp
Guard.Against.LengthOutOfRange("abc", 2, 4); // passes
Guard.Against.LengthOutOfRange("a", 2, 4); // throws
Guard.Against.LengthOutOfRange("abcde", 2, 4); // throws
```

**Comment by HamidRezaAshkiyan** [comment]
Hi Ardalis,
Can I work on this?

**Comment by ardalis** [comment]
All yours; sorry I missed your toolong implementation yesterday.

**Comment by HamidRezaAshkiyan** [comment]
Thanks, also I've refactored the implementation to use other guardCluases and be smaller. 
Please let me know if anything needs to improve or change.
