### ISSUE TITLE
Typo in the StringTooLong error message

### ISSUE THREAD

**Issue by tarioma** [ardalis/GuardClauses#340]
Version 4.4.0

Guard.Against.StringTooLong - error message with a typo.
$"Input {parameterName} with length {input.Length} is too long. **Maxmimum** length is {maxLength}."

**Comment by ardalis** [comment]
Good catch - want to make a PR or let someone else get it?

**Comment by tarioma** [comment]
Sorry, I didn't quite understand you.

The problem is here: https://github.com/ardalis/GuardClauses/blob/main/src%2FGuardClauses%2FGuardAgainstStringLengthExtensions.cs#L56

**Comment by peterblazejewicz** [comment]
fixed in #344
