### ISSUE TITLE
Add custom NotFoundException error message

### ISSUE THREAD

**Issue by nsosoares** [ardalis/GuardClauses#349]
I would like to add a custom message to NotFoundException as sometimes it is necessary to customize a message for business reasons and another language. Do you find it interesting?

**Comment by ardalis** [comment]
Support for this is coming; I think it will be in the next release.

However, I recommend watching this as it sounds like you may be confusing validation with guard clauses:

https://youtu.be/dpPcnAT7n7M?si=fALnlVrJElJKsQbR

**Comment by nsosoares** [comment]
Yes, I will watch, thank you very much for the answer.
