### ISSUE TITLE
Add Guard.Against.Default

### ISSUE THREAD

**Issue by vertonghenb** [ardalis/GuardClauses#36]
Altough we can always extend the clauses, it would be nice to have a Guard.Against.Default() clause, out of the box.

**Comment by dvanherten** [comment]
Interesting. I'm curious about your use case for needing a check against Default<T>. 

I have to imagine it is something covering an object parameter where it could be an int or what not behind the scenes, but without knowing the type, how do you know that false/zero/"" are not valid values in every instance? What's the method you are putting guards on that takes such a generic parameter where you still have enough context such that you know you don't want those values?

Not necessarily against the idea, just honestly curious of the specific example where the need comes up.

**Comment by vertonghenb** [comment]
- Reference Types `Guard.Against.Null`
- int `Guard.Against.Zero`
- decimal `Guard.Against.Zero`
- string `Guard.Against.Empty`
- ...
All these could be combined to a `Guard.Against.Default`

**Comment by ardalis** [comment]
Yes but that seems less clear, so how is it helpful?

**Comment by terryjbutler** [comment]
I could see a case for using such code for the logic behind the scenes, but as for using it as the main syntax, as @ardalis says, it is less clear. 

I think the explicit language (Zero, Empty, Null, etc) better demonstrate the context and intent.

**Comment by vertonghenb** [comment]
I do get the point of being more expressive, but most of the time you already know the datatype of the object you're validating. So I don't see why the intent is less clear.

**Comment by ardalis** [comment]
I'm not opposed to having a single method behind-the-scenes that the others call. I could even be convinced to expose `.Against.Default` publicly. But I definitely wouldn't favor replacing the more descriptive calls with it, because to me it seems too assume more knowledge from the developer. Sure, most/all developers should probably know the defaults for the types in question, but it adds cognitive load for them ("Is the default for string an empty string or null?") instead of just being explicit.

**Comment by vertonghenb** [comment]
Well I would leave the Guards.Against.Null and other variants as is, I like their descriptive nature in most of the cases, but  I'd just add a `Guard.Against.Default`, which in some cases is enough.

**Comment by ardalis** [comment]
Do you want to submit a PR with it? Initially just have it be its own separate thing, don't rewire other guard clauses to use it. I'd accept that PR.

**Comment by vertonghenb** [comment]
@ardalis sure, I'll see what I can do this weekend.

**Comment by ardalis** [comment]
Any update on this?
