### ISSUE TITLE
Question: XML comments

### ISSUE THREAD

**Issue by fiseni** [ardalis/GuardClauses#44]
I'm preparing few packages, and I usually practice generating documentation files for XML comments. I just noticed the PRs in this project are still open, so I'm keen to understand the best way to do this. Most probably there are better approaches, so I look forward to implement better strategies in my projects.

Any comment would be appreciated. Thanks.

**Comment by ardalis** [comment]
I'm not sure what you're asking. Are you wondering why XML comments aren't used in this project, or ?

**Comment by fiseni** [comment]
Sorry if I was not clear.
Ardalis.GuardClauses nuget package does not contain the documentation file, therefore intelisense of summary comments for your methods doesnt appear at all (I dont know if you have noticed that).
I just recently started using this package, I spot that, and just quickly created 2 PR for this project. I did it in a way I do for my own packages.
I noticed PRs are open, I was just wondering if there is a better approach , so I can adopt it too :)

**Comment by AlexanderJohnston** [comment]
Hello, I echo @fiseni and am curious what you think about fixing the XML comments.

**Comment by ardalis** [comment]
Sounds good - I'll review the PRs next chance I get and most likely will accept them and publish a new version. Thanks!

**Comment by ardalis** [comment]
This issue isn't linked to any PRs but I think they've all been merged at this point. Closing but feel free to reopen if necessary.
