### ISSUE TITLE
Add Guard.Against.Negative ?

### ISSUE THREAD

**Issue by elendil-software** [ardalis/GuardClauses#50]
I wonder if it would make sense to add a Guard.Against.Negative Clause ?

To avoid negative values I could use an `uint` type. But in some situation I prefer to use `int`. Especially when the input value come from outside of my projects to avoid the need of cast.

If this suggestion make sense I can do a pull request.

**Comment by ardalis** [comment]
Sure, sounds like an easy one.

**Comment by ardalis** [comment]
This is done.
