### ISSUE TITLE
Enum OutOfRange : allow to input as T

### ISSUE THREAD

**Issue by elendil-software** [ardalis/GuardClauses#51]
With `Guard.Against.OutOfRange<TestEnum>` it is possible to check that an int is a valid value for the `TestEnum` enum.

If a method parameter is already of type `TestEnum`, to check it I have to do :

`Guard.Against.OutOfRange<TestEnum>((int)myEnumParam, nameof(myEnumParam));`

Adding a new method `OutOfRange<T>(this IGuardClause guardClause, T input, string parameterName) where T : Enum`

would allow to do :
`Guard.Against.OutOfRange(myEnumParam, nameof(myEnumParam));`

**Comment by AFM-Horizon** [comment]
Seems pretty handy to be able to pass in the Enum directly.  I can have a go at this if people think It's a feature worth having!?

**Comment by ardalis** [comment]
I'd be happy to have one of you submit a PR for this.

**Comment by AFM-Horizon** [comment]
@elendil-software You got first dibs on this, being your idea and all!, otherwise if you want to palm this off to a noob I'd be happy to take care of it for you.

**Comment by elendil-software** [comment]
@AFM-Horizon @elendil-software 
OK, I'll do a PR

**Comment by ardalis** [comment]
This is done as well.
