### ISSUE TITLE
README file out of date with current Guard Methods

### ISSUE THREAD

**Issue by AFM-Horizon** [ardalis/GuardClauses#55]
Hi,  I opened this as an issue mainly as I'm not sure what the procedure is with updating the README.md file.  Does it need to be updated with the same procedure as a code change with a new version (1.3.4) and Git Release? I'm assuming this is the case as it is included with the project but am not sure!
Thanks.

**Comment by ardalis** [comment]
It doesn't need a new release number or anything, but updates can be sent as pull requests. If you make a PR that adds more methods that should be covered in the PR, you can add the README updates in the PR with the feature.

**Comment by AFM-Horizon** [comment]
Thanks for clarifying.
