### ISSUE TITLE
Add C# 8 Nullable Reference Types annotations

### ISSUE THREAD

**Issue by jnm2** [ardalis/GuardClauses#56]
Without using `object?` and adding System.Diagnostics.CodeAnalysis annotations, the C# compiler will not recognize `Guard.Against.Null` as a null check. This will require users of the library to use `!` afterwards to silence the warning they get if they treat the value as non-null after the check.

https://twitter.com/conner_orth/status/1219885690772738048 (/cc @ConnerOrth)

I can help with this if you'd like.

Also see "What should library authors do?" in https://devblogs.microsoft.com/dotnet/embracing-nullable-reference-types/.

**Comment by ardalis** [comment]
Thanks, a PR would be great. I don't think it's a huge change.
