### ISSUE TITLE
when to use guard clauses and when to return status result instead?

### ISSUE THREAD

**Issue by kdakan** [ardalis/GuardClauses#58]
Hi, I know throwing exceptions and using guard clauses simplify the code a lot. But, can you give a guidance on when to use them and when not to use them, and instead return status result object for example. Like, I don't see validation libraries throwing exceptions, should I use or avoid using guard clauses that throw exceptions in my business (domain) layer, maybe for performance reasons?

**Comment by shanerogers** [comment]
Hey @kdakan the way I see it is that you guard your components to fail fast. Low-level components should not be able to process/execute when in an invalid state. Validation etc should be performed at a higher level, for example, the controller level. If it is an invalid HTTP request. Then return a bad request. If a low-level component fails. Then more likely it will ultimately return a HTTP status code of 500.

**Comment by AFM-Horizon** [comment]
A validation error is something you can regularly expect, which is why they don't throw exceptions. Exceptions should be used in exceptional circumstances, where not stopping the flow of the program could lead to objects being left in a bad state. At least thats my understanding!

**Comment by kdakan** [comment]
@shanerogers , I translate what you’ve said as: Validation and other api layer (controller, middleware) code should not throw exceptions, but other layers (business/domain and infrastructure layers) should use/throw exceptions. Is this what you mean?

**Comment by kdakan** [comment]
@AFM-Horizon , so you say validation is to keep objects in good state, what about business (domain) objects, which change their state when we call its public methods, in ehich there are checks & business rules to check. Should that be considered as validation also, and would I throw or not throw exceptions in my business objects?

**Comment by shanerogers** [comment]
> @shanerogers , I translate what you’ve said as: Validation and other api layer (controller, middleware) code should not throw exceptions, but other layers (business/domain and infrastructure layers) should use/throw exceptions. Is this what you mean?

Yes. As others have stated. Validation is expected and ideally should throw exceptions. Although fluent validation does this. If you use their auto wire up magic. That’s another conversation. Lol

Guard clauses. This should guard you against things that shouldn’t happen. I use them often. Especially when creating a lib to reuse. Makes it hard to get wrong when being used by others. Again fail fast. 

I see guard clauses helping when developing. Generally not something that is seen as a problem running in production

**Comment by kdakan** [comment]
@shanerogers I'm ok with that guidance, which is similar to what I was thinking, for performance reasons not to use exceptions in the outermost public API (webapi controller in the case of web services), where anyone can and will call with bad data arguments. But, lower layers (business and infrastructure) can also be called frequently with invalid arguments (that are more business rule based, and cannot be checked at the outermost controller layer). And you don't know how frequent your public libraries are going to be called, with bad arguments, even in production. As an example, a financial calculator library can be called from anywhere in the program, and with bad arguments. I would think twice if I should throw exception or rather return a result object with status, in my guard clause. What if it is being used in an e-commerce site, called 1000 times a second, with 10% of the calls with some wrong arguments, which can only be validated by going to a data store, thus not inside the controller? I cannot throw exceptions in this case, because the performance would suffer. And the second part of your first comment, that we can return 500 in deeper layers of the application, is not true if this is a business rule violation, then we should return bad request. Bad request error means don't try this again with the same arguments in your request, which is true for business rules. 500 would mean, there was an error, but not on your side, so you could later retry your request with the same arguments.

**Comment by ardalis** [comment]
It's up to you how you want to handle bad input, but in general I agree with others on this thread. Validation is typically done for user input, which as we know can be all kinds of bad. One reason for performing validation (aside from preventing bad data, etc.) is to prevent exceptions in your system. Once a request has made it through your validation layer(s), theoretically your system should be able to perform the requested operations. If something still is missing or entirely out of the bounds you expect, that's likely an exception event at that point, and that's where guard clauses are helpful.

**Comment by shanerogers** [comment]
> @shanerogers I'm ok with that guidance, which is similar to what I was thinking, for performance reasons not to use exceptions in the outermost public API (webapi controller in the case of web services), where anyone can and will call with bad data arguments. But, lower layers (business and infrastructure) can also be called frequently with invalid arguments (that are more business rule based, and cannot be checked at the outermost controller layer). And you don't know how frequent your public libraries are going to be called, with bad arguments, even in production. As an example, a financial calculator library can be called from anywhere in the program, and with bad arguments. I would think twice if I should throw exception or rather return a result object with status, in my guard clause. What if it is being used in an e-commerce site, called 1000 times a second, with 10% of the calls with some wrong arguments, which can only be validated by going to a data store, thus not inside the controller? I cannot throw exceptions in this case, because the performance would suffer. And the second part of your first comment, that we can return 500 in deeper layers of the application, is not true if this is a business rule violation, then we should return bad request. Bad request error means don't try this again with the same arguments in your request, which is true for business rules. 500 would mean, there was an error, but not on your side, so you could later retry your request with the same arguments.

Hey @kdakan What you said makes sense. I've worked on all sorts of APIs and applications alike. If you have business logic that validates if you can or cannot do something. You have two choices either throw an exception or return a collection of errors via the notification pattern (or something). Depending I've done both. Throwing exception as an advantage in that the code doesn't have error code type objects returned through the stack. I just depends. ;0

**Comment by ardalis** [comment]
Closing this as the discussion seems to have resolved.
