### ISSUE TITLE
Add overloads that don't have parameterName parameter

### ISSUE THREAD

**Issue by NRKirby** [ardalis/GuardClauses#64]
I noticed that all of the examples in the [README](https://github.com/ardalis/GuardClauses/blob/master/README.md) use the same `parameterName` as the `input`. I wonder if most often athis library will be used like this, with the same `parameterName` as `input` (and therefore a lot of duplication).

A simpler approach might be to have overloads for each method in  [GuardClauses.cs](https://github.com/ardalis/GuardClauses/blob/master/src/GuardClauses/GuardClauseExtensions.cs) that don't have the `parameterName` parameter, and uses the `nameof` the input. 

I just forked the repo and have an example of what I mean in [this commit](https://github.com/NRKirby/GuardClauses/commit/93b097b7d283ed61bf6dbd9b4577e5b2d90f2ba3)

With that in mind, would you accept a pull request which adds an overload with a simpler signature for each of the methods in the library? 

If you would, I will happily do one!

Nick

**Comment by ardalis** [comment]
I commented on your commit. If you can make it work so it's not always just the argument name within GuardClauses (but the actual argument name being checked) I'd gladly accept such a PR.

**Comment by NRKirby** [comment]
Ah I think I was a bit hasty on this. This seems so obvious now (I didn't actually run the code). I will have a think about if this is possible although I'm sure you've been thinking about this a lot longer and harder than I have!

**Comment by ardalis** [comment]
No worries, it's definitely a worthwhile idea to pursue! Cheers.
