### ISSUE TITLE
In case of Enum, OutOfRange should throw InvalidEnumArgumentException

### ISSUE THREAD

**Issue by elendil-software** [ardalis/GuardClauses#66]
Hi,

In the case of an enum, OutOfRange should throw an [InvalidEnumArgumentException](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.invalidenumargumentexception) instead of an `ArgumentOutOfRangeException`

What do you think ?

**Comment by ardalis** [comment]
Agreed. You want to make a pull request, @elendil-software ?

**Comment by elendil-software** [comment]
There is a problem, this exception does not exist in .NET Standard 1.1 : https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.invalidenumargumentexception?view=netcore-3.1&viewFallbackFrom=netstandard-1.1
I don't think it will be possible to do the change.

**Comment by ardalis** [comment]
Ok maybe this is something we can target for a 3.0 release, which can depend on a higher version of netstandard.

**Comment by ShadyNagy** [comment]
PR -> #78

**Comment by ardalis** [comment]
This is in v3.0.0 since it's a breaking change: https://www.nuget.org/packages/Ardalis.GuardClauses/
