### ISSUE TITLE
LengthOutOfRange

### ISSUE THREAD

**Issue by pauldbentley** [ardalis/GuardClauses#69]
Would you consider a method such as `LengthOutOfRange(min, max)` for this package?

I don't know if this is too close to validation?

My use case is I often have value objects or entity properties which need to be a certain length i.e. a product code must be not null, not empty or white space, and exactly 5 characters

```
public const int MinValueLength = 5;

public const int MaxValueLength = 5;

public ProductCode(string value)
{
	Guard.Against.NullOrWhiteSpace(value, nameof(value));
	Guard.Against.LengthOutOfRange(value, nameof(value), MinValueLength, MaxValueLength);

	this.Value = value;
}
```

**Comment by ardalis** [comment]
The package is extensible locally, so you could certainly create the guards yourself and use the rest of the package along with your own guards.

As for whether they seem general purpose enough to include in the default set of guards that ship with the package, I don't know. You're right, it does start to feel more and more like validation, which honestly the line between guard clauses and validators is pretty gray already. I think if people found it useful and it didn't add confusion it would be fine to include. I don't think I would call it `LengthOutOfRange` though - sounds like just `OutOfRange` would be the more general purpose approach, agreed?

**Comment by pauldbentley** [comment]
I have it implemented locally in a number of projects so I thought I’d raise it.  It is borderline validation as you say.  Validation at the UI end could check the input, but that relies on the validation being in place.  If a product code must be 5 characters then the entity should protect its invariants and guard against invalid values otherwise the entity could become invalid.  Probably not a general enough case for this package the more I’ve thought about it. Thanks for your input.
