### ISSUE TITLE
IGuardAssignment<T> Interface

### ISSUE THREAD

**Issue by Hosch250** [ardalis/GuardClauses#72]
# Proposal for creating an `IGuardAssignment<T>` interface.

Currently, you can't chain guard clauses, which reduces the value when using it in a constructor:

```
    public class Order
    {
        private string _name;
        private int _quantity;
        private long _max;
        private decimal _unitPrice;
        private DateTime _dateCreated;

        public Order(string name, int quantity, long max, decimal unitPrice, DateTime dateCreated)
        {
            _name = Guard.Against.NullOrWhiteSpace(name, nameof(name));
            _quantity = Guard.Against.NegativeOrZero(quantity, nameof(quantity));
            _max = Guard.Against.Zero(max, nameof(max));
            _unitPrice = Guard.Against.Negative(unitPrice, nameof(unitPrice));
            _dateCreated = Guard.Against.OutOfSQLDateRange(dateCreated, nameof(dateCreated));
        }
    }
```

## Proposed Implementation

```
    public interface IGuardAssignment<out T>
    {
        public T Value { get; }
    }

    public class GuardAssignment<T> : IGuardAssignment<T>
    {
        private GuardAssignment() { }

        public T Value { get; private set; } = default!;

        public static IGuardAssignment<T> WithValue(T value)
        {
            return new GuardAssignment<T>
            {
                Value = value
            };
        }
    }

    public static class GuardAssignmentExtensions
    {
        public static IGuardAssignment<T> AgainstNegative<T>([JetBrainsNotNull] this IGuardAssignment<T> guardClause, [JetBrainsNotNull] string parameterName) where T : struct, IComparable
        {
            if (guardClause.Value.CompareTo(default(T)) < 0)
            {
                throw new ArgumentException($"Required input {parameterName} cannot be negative.", parameterName);
            }

            return guardClause;
        }

        public static IGuardAssignment<T> AgainstZero<T>([JetBrainsNotNull] this IGuardAssignment<T> guardClause, [JetBrainsNotNull] string parameterName) where T : struct
        {
            if (EqualityComparer<T>.Default.Equals(guardClause.Value, default))
            {
                throw new ArgumentException($"Required input {parameterName} cannot be zero.", parameterName);
            }

            return guardClause;
        }

        public static IGuardAssignment<T> AgainstExpression<T>([JetBrainsNotNull] this IGuardAssignment<T> guardClause, [JetBrainsNotNull] Func<T, bool> func, [JetBrainsNotNull] string message) where T : struct
        {
            if (func(guardClause.Value))
            {
                throw new ArgumentException(message);
            }

            return guardClause;
        }
    }
```

## Usage

```
    public class Foo
    {
        private readonly int _x;

        public Foo(int x)
        {
            _x = GuardAssignment<int>.WithValue(x)
                .AgainstNegative(nameof(x))
                .AgainstZero(nameof(x))
                .AgainstExpression(x => x != 5, "5 is not a valid number.")
                .Value;
        }
    }
```

## Questions:

- Is this useful outside of assignments?
Normal guard clauses can't be chained, since they don't return `IGuardClause`. Each guard must be specified individually. Normal guards can currently be used as assignments since they return the checked value. (The `Null` guard clause currently only returns `object`, though, which requires a cast for typed assignments). My proposal can be used outside of assignments as well; it would just look like:

```
        public void Foo(int x)
        {
            GuardAssignment<int>.WithValue(x)
                .AgainstNegative(nameof(x))
                .AgainstZero(nameof(x));

            // ...
        }

        // or

        public void Foo(int x)
        {
            _ = GuardAssignment<int>.WithValue(x)
                .AgainstNegative(nameof(x))
                .AgainstZero(nameof(x));

            // ...
        }
```

- The `Against` static member is gone. Why is that?
I considered three options when making this proposal. The first one looked like `GuardAssignment.Against.Check(input, argName)`. This one had the implementation problem of protecting against someone doing `GuardAssignment.Against.Value`. We needed to ensure that the last extension method called assigned the `Value` property. It also had the issue of having the value accessible from the guard class instance, but needing to repeatedly pass it in to each extension method. The second one looked like `new GuardAssignment(input).Check(argName)`. This one had the issue of allowing people to work directly from the class instead of just from the interface. Hence, my current implementation.

## Notes

Guards are evaluated in a first to last order.

**Comment by antmdvs** [comment]
I usually appreciate the terseness, readability and dev experience of fluent APIs but for some reason I'm not sure if it feels right for guard clauses. I did a little hunting for criticism and [found this sentiment echoed here](https://github.com/adamralph/liteguard#no-fluent-api).

However, that repo author's counterarguments are perf-focused and probably have negligible impact for most app code. Also, his library [doesn't have any guards except null](https://github.com/adamralph/liteguard#no-business-rule-clauses) so chaining would provide limited convenience there. (BTW, @ardalis ' take on the "no business rules" philosophy [seems to be found here](https://github.com/ardalis/GuardClauses/issues/58#issuecomment-579113944) more or less -- I was curious about that after reading the links.)

After researching, I can't think of a good reason not to implement this. 👍

**Comment by antmdvs** [comment]
One thing to consider during this might be to have separate interfaces for different types (numeric, string, date, object), each having only the extension methods appropriate for those data types so that:
1. The type system can provide compile-time guarantees against incompatible guard clauses.
2. When developer's dot out the expression in the IDE, they are only presented with valid guards for the given type.

**Comment by pauldbentley** [comment]
I would find the assigning capability very useful, if only to reduce the number of lines of code and make similar to the "add null check" _value = value ?? throw new ArgumentNullException();  I will take some more time to consider a response on chaining; in my use of the package its not often that there are multiple guards for the same value.

**Comment by pauldbentley** [comment]
I can't think of many examples, if any, where chaining would be needed.  Do you have more specific cases?

For example:

```
public void Foo(int x)
{
	GuardAssignment<int>.WithValue(x)
		.AgainstNegative(nameof(x))
                .AgainstZero(nameof(x));

        // ..
}
```

Can be currently implemented as:

```
public void Foo(int x)
{
	Guard.Against.ZeroOrNegative(nameof(x));

	// ...
}
```

**Comment by antmdvs** [comment]
> I can't think of many examples, if any, where chaining would be needed. Do you have more specific cases?

👆🏽 I think this is what initially caused me to question the proposal as well. It would be nice to see some stats on usage patterns to validate the need -- the [dependents of this package](https://github.com/ardalis/GuardClauses/network/dependents) would be a start.

**Comment by ardalis** [comment]
I'm on the fence about chaining. I generally appreciate the capability in places where it's useful, but I think I agree with @pauldbentley that it may not be much use here. I don't think I can recall an instance where I would have used it with these guard clauses, myself, for instance.

There are a couple of independent "features" up for discussion here:

1. Performing assignment and guard clause in a single statement. This is the most obviously useful feature, especially in constructors.
2. Being able to chain together multiple guards. Not sure this is useful. Does add more overhead and complexity to the framework.

There was some discussion of support an `IGuardAssignment<T>` interface that supported returning values in parallel with the existing guard clauses. Extensions on this type would just return `T` rather than a chainable instance of `IGuardAssignment<T>` so they wouldn't be chainable, but would support the common constructor assignment use case. To illustrate, this code:

```csharp
public class Foo
{
   private ISomething _service;
   private ISomething2 _service2;
   private ISomething3 _service3;

  public Foo(ISomething service, ISomething2 service2, ISomething3 service3)
  {
    Guard.Against.Null(service, nameof(service));
    Guard.Against.Null(service, nameof(service2));
    Guard.Against.Null(service, nameof(service3));

    _service = service;
    _service2 = service2;
    _service3 = service3;
  }
}
```

would be simplified down to this:

```csharp
public class Foo
{
   private ISomething _service;
   private ISomething2 _service2;
   private ISomething3 _service3;

  public Foo(ISomething service, ISomething2 service2, ISomething3 service3)
  {
    _service = GuardAssignment.Against.Null(service, nameof(service));
    _service2 = GuardAssignment.Against.Null(service2, nameof(service2));
    _service3 = GuardAssignment.Against.Null(service3, nameof(service3));
  }
}
```

An alternate API for this might be:

```csharp
  _service = Guard.Against.Null(service, nameof(service)).Value;
```

The implementation would use generics to eliminate the need for any casts but I would expect in most cases the types involved would be inferred from the argument types, so you wouldn't need to specify the type in the code.

Questions:

Would you find it valuable to be able to do assignment inline with a single guard clause?

Would you find it valuable to be able to chain together multiple guard clauses?

**Comment by pauldbentley** [comment]
Does the `Default` method help with constructor assignment?

```cs
public class Foo
{
    private ISomething _service;
    private ISomething2 _service2;
    private ISomething3 _service3;

    public Foo(ISomething service, ISomething2 service2, ISomething3 service3)
    {
        _service = Guard.Against.Default(service, nameof(service));
        _service2 = Guard.Against.Default(service2, nameof(service2));
        _service3 = Guard.Against.Default(service3, nameof(service3));
    }
}
```

**Comment by ardalis** [comment]
Actually, it's been a while since I've looked at this code closely, most of the existing extensions already return the thing they're evaluating...
https://github.com/ardalis/GuardClauses/blob/master/src/GuardClauses/GuardClauseExtensions.cs

So, there's nothing to prevent doing assignment in one line already. The main thing that started this issue is this one:

```csharp
public static object Null([JetBrainsNotNull] this IGuardClause guardClause, [NotNull, JetBrainsNotNull][ValidatedNotNull] object? input, [JetBrainsNotNull] string parameterName)
        {
            if (null == input)
            {
                throw new ArgumentNullException(parameterName);
            }

            return input;
        }
```
with issue being that it's returning object, not T.

I wonder if we were simply to add a generic extension method (returning T) if that would suffice. We already have that for `NullOrEmpty` collections:

```csharp
public static IEnumerable<T> NullOrEmpty<T>([JetBrainsNotNull] this IGuardClause guardClause, [NotNull, JetBrainsNotNull][ValidatedNotNull] IEnumerable<T>? input, [JetBrainsNotNull] string parameterName)
        {
            Guard.Against.Null(input, parameterName);
            if (!input.Any())
            {
                throw new ArgumentException($"Required input {parameterName} was empty.", parameterName);
            }

            return input;
        }
```

**Comment by pauldbentley** [comment]
>I wonder if we were simply to add a generic extension method (returning T) if that would suffice.

I actually have this already implemented in a set of custom extensions and I was going to raise to you as a potential change as I've used it enough times to think it would be useful.

**Comment by Hosch250** [comment]
> I wonder if we were simply to add a generic extension method (returning T) if that would suffice.

That's what I first pinged you about (privately). Note the examples on your readme already show assignments as being a usecase.

> One thing to consider during this might be to have separate interfaces for different types (numeric, string, date, object), each having only the extension methods appropriate for those data types so that:
>
> 1) The type system can provide compile-time guarantees against incompatible guard clauses.
> 1) When developer's dot out the expression in the IDE, they are only presented with valid guards for the given type.

The use of generics does exactly that.

**Comment by ardalis** [comment]
@Hosch250 

> That's what I first pinged you about (privately). Note the examples on your readme already show assignments as being a usecase.

I know. I think we all agree at this point that's useful. And as far as "adding" support for assignments, that's on me for forgetting we already had that feature. I'm maintaining a lot of projects and haven't touched this one in a while, so... my bad. :)

I agree regarding your comment on generics, too.

**Comment by ardalis** [comment]
Let's do a PR with just the update to the NotNull guard clause, providing a generic alternative, for now. Do you want to do that real quick, @Hosch250 ?

**Comment by ardalis** [comment]
Closing this as:

- Strongly typed generic NotNull assignment is now supported in 2.0.0 release (thanks @Hosch250 for your PR)
- Assignments were added in a previous release
- Chaining is of dubious value and adds overhead

Thanks all for your input!

**Comment by pauldbentley** [comment]
One place I do often "chain" together guards is related to #69 - I often guard against `NullOrWhiteSpace` and `OutOfRange` to check the length of a string input.  When @ardalis and I discussed this it was felt this was too close to validation to be generic enough for this package.  But I do also have a custom `Any()` extension which can run multiple guards:

```cs
public static T Any<T>(this IGuardClause guardClause, T input, Action guards)
{
    guards();
    return input;
}
```

Which can be used as:

```cs
_productCode = Guard.Against.Any(productCode, () =>
{
    Guard.Against.NullOrWhiteSpace(productCode, nameof(productCode));
    Guard.Against.OutOfRange(productCode, nameof(productCode), MinProductCodeLength, MaxProductCodeLength);
 });
```

Again, probably not general enough to be included in the package but thought I'd share my thoughts.

**Comment by ardalis** [comment]
I do think an open-ended expression-based guard could add value. It could be abused, since you could use it for *anything*, but it would eliminate the need for multiple checks in your example above. Something similar to @Hosch250 's code here:

```csharp
public static IGuardAssignment<T> AgainstExpression<T>([JetBrainsNotNull] this IGuardAssignment<T> guardClause, [JetBrainsNotNull] Func<T, bool> func, [JetBrainsNotNull] string message) where T : struct
        {
            if (func(guardClause.Value))
            {
                throw new ArgumentException(message);
            }

            return guardClause;
        }
```

**Comment by ardalis** [comment]
Alternately your approach of multiple guards in combination could work, too, which is somewhat less flexible but more in keeping with using the library of existing guards.

We could consider both, in fact.
