### ISSUE TITLE
Expression Guard

### ISSUE THREAD

**Issue by ardalis** [ardalis/GuardClauses#77]
An Expression-based Guard could be used to provide flexibility and could cover any case not already taken care of by the library, without the need to write your own guard clause method.

```csharp
public static T AgainstExpression<T>([JetBrainsNotNull] this IGuardClause<T> guardClause, [JetBrainsNotNull] Func<T, bool> func, [JetBrainsNotNull] string message) where T : struct
{
    if (func(guardClause.Value))
    {
        throw new ArgumentException(message);
    }
    return T;
}
```

**Comment by fiseni** [comment]
This is nice. Any reason you want to limit this only for "struct"?

**Comment by dsbert** [comment]
Be aware that this can lead to performance issues if abused.

https://github.com/safakgur/guard/issues/13

**Comment by mohaanwrites** [comment]
If someone wants to deal with string properties with custom validations, this will not allow. Otherwise, I've added the required tests. Let me know.

**Comment by wgnf** [comment]
@ardalis do you still want this to be implemented? if so, i'd love to have a go at this :)

**Comment by ardalis** [comment]
yes, if someone wants to implement support for it, I'd look at the PR. Just reference this issue number in the description. Thanks, @wgnf

**Comment by wgnf** [comment]
Just scrolling through code to see how things are done i stumbled upon this one:  
  
https://github.com/ardalis/GuardClauses/blob/main/src/GuardClauses/GuardClauseExtensions.cs#L581-L589

`Guard.Against.InvalidInput` seems to already be the "Expression Guard" that you are mentioning in this issue 🤔

**Comment by wgnf** [comment]
The only thing that is different here is that you mention a `IGuardClause<T>` with a `Value` in that (new) interface, which I'm unable to find.  
  
Or is that the new feature you wanted to implement and I just didn't get the hint? :D @ardalis

**Comment by ardalis** [comment]
Hmm... yeah, that's fair. I think maybe I missed it due to its naming. Ok, let's just say this is done, then. 😃
