### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by scottkuhl** [ardalis/GuardClauses#81]
Release 3.0.0 is showing up in NuGet but there is no official 3.0.0 release here on GitHub.

**Comment by ardalis** [comment]
I think I just fixed this, thanks.

**Comment by elendil-software** [comment]
I would suggest to complete the release note by adding that `OutOfRange` does not throws an `ArgumentOutOfRangeException` anymore but an `InvalidEnumArgumentException`. In the eventuality that someone was catching an `ArgumentOutOfRangeException` this would be a breaking change as it would not be catched anymore.
