### ISSUE TITLE
Feature - Add ability to provide RegEx expressions

### ISSUE THREAD

**Issue by krptodr** [ardalis/GuardClauses#82]
It would be nice to pass regular expression to the Guard.Against method where the expression is processed. Thinking further on the idea, I'm not sure how I would name these methods to help with readability.

**Comment by ardalis** [comment]
`Guard.Against.StringsMatching(RegEx expression)` ?

**Comment by MojtabaKiani** [comment]
I think it must be some thing like this :
 

        public static string BadFormat([JetBrainsNotNull] this IGuardClause guardClause, [JetBrainsNotNull] string input, [JetBrainsNotNull] string parameterName, [JetBrainsNotNull] string regexPattern)
        {
            if (input != Regex.Match(input, regexPattern).Value)
                throw new ArgumentException($"Input {parameterName} was not in required format", parameterName);

            return input;
        }

**Comment by ardalis** [comment]
Want to PR that? Do we like Bad or Invalid format better?

**Comment by MojtabaKiani** [comment]
yep, InvalidFormat is better, I've sent the PR

**Comment by krptodr** [comment]
Here is the method I implemented. I went with @ardalis early implementation the a guard clause

public static void ForRegExMatch(string pattern, string value, string parameterName, string message = null)
        {
            if (value == null)
                return;

            if (new Regex(@pattern).IsMatch(value))
                return;

            if (string.IsNullOrEmpty(message))
                throw new ArgumentOutOfRangeException(parameterName);
            throw new ArgumentOutOfRangeException(parameterName, message);
        }
