### ISSUE TITLE
Discussion - Core Guards and duplication

### ISSUE THREAD

**Issue by dvanherten** [ardalis/GuardClauses#9]
Currently we are in a state of duplication when it comes to the method calls. We establish the guards provided by the library as CoreGuard extension methods and then provide a shortcut to get to it right off of Guard. Starting from a clean slate I may have exposed Against on the static Guard class and left the short cuts off. They were maintained mostly for backwards compatibility as the package had been release already. That was my general thinking during the implementation at least. That said, there are pros and cons to that approach.

Possible options: 

**Option 1:**
Keep core guards straight on Guard.cs as the static methods they originally were and leave Against as a pure extension point.
Pro: 
- This library can be built out such that it's right off Guard for the majority of main use cases.
- Extension methods of Against become obvious that they are an extension of the library.
- No core extension methods means less public classes just to house extension methods.

Cons: 
 - Feels odd that Against would be empty by default.
 - On a larger team that may not realize how the library works may not realize Against has more Guards.

**Option 2:**
Remove guards on Guard.cs and only have the Against extension. All guards will start with Guard.Against.
Pro:
 - One syntax to rule them all
 - Less duplication

Cons: 
 - Always jumping through Against (Not sure this is really a con)
 - No way to tell custom from built-in Guards. (might be a pro?)

**Option 3:**
Keep the method duplication with the shortcut, but separate Guards into their own partial classes.
Pros: 
 - Majority of Guards are likely shown immediately after Guard in intellisense.
 - They still also show in Against so you can't miss it.

Cons:
 - Lots of public static classes polluting intellisense
 - Still making the shortcut
 - Still need duplication of the tests to ensure correctness. Helper of some kind may help here although I can't picture it in my head yet.
 - On a larger team that may not realize how the library works may not realize Against has more Guards.

An example leveraging partial classes could look something like this:
```c#
public partial class Guard
{
    /// <summary>
    /// Throws an ArgumentNullException if input is null.
    /// </summary>
    /// <param name="input"></param>
    /// <param name="parameterName"></param>
    /// <exception cref="ArgumentNullException"></exception>
    public static void AgainstNull(object input, string parameterName) => Guard.Against.Null(input, parameterName);
}

public static class NullGuard
{
    /// <summary>
    /// Throws an ArgumentNullException if input is null.
    /// </summary>
    /// <param name="guardClause"></param>
    /// <param name="input"></param>
    /// <param name="parameterName"></param>
    /// <exception cref="ArgumentNullException"></exception>
    public static void Null(this IGuardClause guardClause, object input, string parameterName)
    {
        if (null == input)
        {
            throw new ArgumentNullException(parameterName);
        }
    }
}
```

Technically 1& 2 are breaking changes as we'd be removing some of the default methods. I've left that out of the con list for the purposes of this discussion. 

_I'm honestly not sure at this point which path I prefer or if there's a path I'm not seeing so I'm probably going to step away for a bit and see if this sparks some discussion._

**Comment by ardalis** [comment]
_Not sure how I can possibly keep up with this busy thread, but I'll try..._ 😃 

Thanks for writing this up, @dvanherten . I appreciate it. I've been mulling it over and although Option 2 is a breaking change, we have virtually 0 users of the Nuget project thus far, so the impact should be minimal. I've been thinking about how the `Guard.Against.Something` will be more consistent and will ensure that our documentation needs don't double and folks will be able to discover all of the available extensions, both built-in and their own custom ones, using the same procedure/syntax.

Dave - do you want to do a PR for this change, or shall I? Anybody have any objections to option 2?

**Comment by ardalis** [comment]
Since I want to use this in a couple of other projects, I'm going to go ahead and jump on this.

**Comment by ardalis** [comment]
Now live on Nuget. I rev'd it to 1.1.0 since it had breaking changes.
https://www.nuget.org/packages/Ardalis.GuardClauses/1.1.0

**Comment by dvanherten** [comment]
Very nice. I was away this afternoon/evening so wasn't able to comment, but I had also started leaning towards option 2 so this is great.
