### ISSUE TITLE
Custom message as optional parameter or overload

### ISSUE THREAD

**Issue by apm1grb** [ardalis/GuardClauses#97]
In the past, I have used SolidStack.Core.Guards for guard clauses. This library allows the definition of own error messages which absolutely makes sense sometimes.

Is something similar planned for this lib in the future?

**Comment by ardalis** [comment]
Sure this seems like a pretty simple thing to add.

**Comment by apm1grb** [comment]
A colleague and I could step in.
But if you have currently an idea of how to proceed and how the interface extension should look like, please let us know.

**Comment by ardalis** [comment]
I think you would just need to go through all of the `GuardClauseExtensions.cs` guards and add a `string? message` parameter which you then pass into the exception being thrown. For example, this would be the new Null<T> extension:

```
        public static T Null<T>([JetBrainsNotNull] this IGuardClause guardClause, [NotNull, JetBrainsNotNull][ValidatedNotNull] T input, [JetBrainsNotNull] string parameterName, string? message = null)
        {
            if (input is null)
            {
                throw new ArgumentNullException(parameterName, message);
            }

            return input;
        }
```

Do you want to do a PR for this?
